name: Build and deploy with evidence

on:
  [push, workflow_dispatch]

permissions:
  id-token: write
  contents: read

jobs:
  Docker-build-with-evidence:
    runs-on: ubuntu-latest
    steps:
      - name: Install jfrog cli
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ vars.ARTIFACTORY_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}

      - uses: actions/checkout@v4

      - name: Log in to Artifactory Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.ARTIFACTORY_URL }}
          username: ${{ secrets.JF_USER }}
          password: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          install: true

      - name: Build Docker image-test and push to Artifactory with evidence
        run: |
          URL=$(echo ${{ vars.ARTIFACTORY_URL }} | sed 's|^https://||')
          REPO_URL=${URL}'/ds-docker-dev-virtual'
          docker build --build-arg REPO_URL=${REPO_URL} -f Dockerfile . \
          --tag ${REPO_URL}/ds:${{ github.run_number }} \
          --output=type=image --platform linux/amd64 --metadata-file=build-metadata --push
          
          jf rt build-docker-create \
            ds-docker-dev-local \
            --image ds:${{ github.run_number }} \
            --image-file build-metadata \
            --build-name ${{ vars.BUILD_NAME }} \
            --build-number ${{ github.run_number }} \
            --project ds
#      - name: Evidence on docker
#        run: |
##          echo '{ "actor": "${{ github.actor }}", "date": "'$(date -u +"%Y-%m-%dT%H:%M:%SZ")'" }' > sign.json
##          jf evd create --package-name example-project-app --package-version ${{ github.run_number }} --package-repo-name ds-docker-dev-local \
##            --key "${{ secrets.PRIVATE_KEY }}"  --key-alias KEY-ALIAS \
##            --predicate ./sign.json --predicate-type https://jfrog.com/evidence/signature/v1
#          echo 'üîé Evidence attached: `signature` üîè '

      - name: Upload readme file
        run: |
          jf rt upload ./README.md ds-generic-dev-local/readme/${{ github.run_number }}/ --build-name ${{ vars.BUILD_NAME }} --build-number ${{ github.run_number }}
#          jf evd create --subject-repo-path example-project-generic-dev/readme/${{ github.run_number }}/README.md \
#            --key "${{ secrets.PRIVATE_KEY }}" --key-alias KEY-ALIAS  \
#            --predicate ./sign.json --predicate-type https://jfrog.com/evidence/signature/v1
#            --project ds


      - name: Collecting Information from Git
        run: jf rt build-add-git ${{ vars.BUILD_NAME }} ${{ github.run_number }} --project ds

      - name: Collecting Environment Variables
        run: jf rt build-collect-env ${{ vars.BUILD_NAME }} ${{ github.run_number }} --project ds

      - name: Publish build info
        run: jfrog rt build-publish ${{ vars.BUILD_NAME }} ${{ github.run_number }} --project ds
